---
title: "Iterations and listcols"
output: github_document
date: "2024-10-29"
---

```{r setup, include = FALSE}
library(tidyverse)
library(rvest)
```

## Lists 

You can put anything in a list. 
```{r}
l = list(
  vec_numeric = 5:8,
  mat         = matrix(1:8, 2, 4),
  vec_logical = c(TRUE, FALSE),
  summary     = summary(rnorm(1000)))

```

```{r}
l
l$vec_numeric
l[[1]]
l[[1]][1:3]
```

## 'for' loop

Create a new list. 

```{r}
list_norms = 
  list(
    a = rnorm(20, 3, 1),
    b = rnorm(20, 0, 5),
    c = rnorm(20, 10, .2),
    d = rnorm(20, -3, 1)
  )

```

```{r}
list_norms
```

Pause and get my old function. 

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```

I can apply that function to each list element. 

```{r}
mean_and_sd(list_norms[[1]])
mean_and_sd(list_norms[[2]])
mean_and_sd(list_norms[[3]])
mean_and_sd(list_norms[[4]])
```

Let's use a for loop: 

```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = mean_and_sd(list_norms[[i]])
}
```

## Let's try map! 

```{r}
output = map(list_norms, mean_and_sd)
```

What if you want a different function? 

```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = median(list_norms[[i]])
}

output = map(list_norms, median)
```

```{r}
output = map_dbl(list_norms, median, .id = "input")
```

```{r}
output = map_dfr(list_norms, mean_and_sd, .id = "input")
```

## List Columns! 

```{r}
listcol_df = 
  tibble(
    name = c("a", "b", "c", "d"),
    samp = list_norms
  )
```

```{r}
listcol_df |> pull(name)
listcol_df |> pull(samp)
```

Let's try some operations. 

```{r}
listcol_df$samp[[1]]
mean_and_sd(listcol_df$samp[[1]])
```

Can I just... map? 

```{r}
map(listcol_df$samp, mean_and_sd)
```

So... can I add a list column? 

```{r}
listcol_df = 
  listcol_df |> 
  mutate(summary = map(samp, mean_and_sd))

listcol_df
```

